language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

install:
    - pip install -r testing_requirements.txt
    - travis_retry pip install coverage

script:
    - virtualenv --version
    - coverage --version
    - cram --version
    - coverage run --source=bibpy -m pytest --verbose

    - python setup.py install
    - python examples/crossref_expansion.py
    - python examples/field_conversion.py
    - python examples/entry_formatting.py
    - python examples/requirements_check.py
    - python examples/string_expansion.py

after_success:
    - coveralls

branches:
    only:
        - master
