language: python
dist: precise

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"

install:
    - pip install -r testing_requirements.txt

    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install 'virtualenv<14'; fi

#before_script:
    #- pep257 --ignore=D102,D103,D211,D400 .

script:
    - virtualenv --version
    - coverage --version
    - cram --version
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then coverage run --source=bibpy -m py.test --verbose; fi
    #- cram --verbose tests/bin/test_bib*.t

after_success:
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then coveralls; fi

branches:
    only:
        - master
