language: python
dist: precise

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"

install:
    - pip install -r testing_requirements.txt
    - travis_retry pip install coverage

#before_script:
    #- pep257 --ignore=D102,D103,D211,D400 .

script:
    - virtualenv --version
    - coverage --version
    - cram --version
    - coverage run --source=bibpy -m py.test --verbose
    - python examples/crossref_expansion.py
    - python examples/field_conversion.py
    - python examples/entry_formatting.py
    - python examples/requirements_check.py
    - python examples/string_expansion.py
    #- cram --verbose tests/bin/test_bib*.t

after_success:
    - coveralls

branches:
    only:
        - master
