language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"

install:
    - pip install -r test-requirements.txt
    - travis_retry pip install coverage

script:
    - virtualenv --version
    - coverage --version
    - cram --version
    - python setup.py install

    - cram tests/scripts/test_bibformat.t
    - cram tests/scripts/test_bibgrep.t
    - cram tests/scripts/test_bibstats.t

    - python examples/crossref_expansion.py
    - python examples/field_conversion.py
    - python examples/formatting.py
    - python examples/entry_formatting.py
    - python examples/requirements_check.py
    - python examples/string_expansion.py

    - coverage run --source=bibpy -m pytest
    - coverage report

after_success:
    - coveralls

branches:
    only:
        - master
