name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Lint
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          tox -e lint

  test:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3"]
      steps:
        - uses: actions/checkout@v2
        - name: Set up python ${{ matrix.python }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r test-requirements.txt
        - name: Run tests
          run: tox -e ALL

  docs:
    if: github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - run: tox -e docs
